export const barData = [ 
  { name: 'Alojamiento', 
      icon: 'IoBedOutline', 
    title: 'Alojamiento',  
    text: 'Tucumán cuenta con una gran variedad de Hoteles, Cabañas, Estancias Rurales, etc., que ofrecen una gama de opciones de acuerdo a tu presupuesto y preferencias. Podés consultar el listado de alojamientos aquí. ',  
    img: '/images/planifica/alojamiento.jpg', 

  },
     
  { name: 'Transporte urbano', 
      icon: 'IoBusOutline',  
    title: 'Transporte urbano',  
    text: 'Si querés conocer todos los atractivos que Tucumán tiene para ofrecerte y no contás con vehículo propio, o no querés conducir para no perderte todas las maravillas del paisaje, no te preocupes. Aquí te dejamos los horarios de los micros a todos los puntos turísticos de nuestra provincia, para que puedas armar tu propio itinerario.',  
    img: '/images/planifica/transportes.jpg'  }, 
  { name: 'Alquiler de Autos', 
      icon: 'AiOutlineCar',  
    title: 'Alquiler de Autos',  
    text: 'Tucumán cuenta con una gran variedad de Hoteles, Cabañas, Estancias Rurales, etc., que ofrecen una gama de opciones de acuerdo a tu presupuesto y preferencias. Podés consultar el listado de alojamientos aquí. ',   
    img: '/images/planifica/alojamiento.jpg'  }, 
  { name: 'Prestadores activos', 
      icon: 'MdOutlineHiking',  
    title: 'Prestadores activos',  
    text: 'Si querés conocer todos los atractivos que Tucumán tiene para ofrecerte y no contás con vehículo propio, o no querés conducir para no perderte todas las maravillas del paisaje, no te preocupes. Aquí te dejamos los horarios de los micros a todos los puntos turísticos de nuestra provincia, para que puedas armar tu propio itinerario.',   
    img: '/images/planifica/alojamiento.jpg'  }, 
  { name: 'Agencias',  
      icon: 'AiTwotoneShop',  
    title: 'Agencias',  
    text: 'Tucumán cuenta con una gran variedad de Hoteles, Cabañas, Estancias Rurales, etc., que ofrecen una gama de opciones de acuerdo a tu presupuesto y preferencias. Podés consultar el listado de alojamientos aquí. ',   
    img: '/images/planifica/alojamiento.jpg'  }, 
  { name: 'Guías de turismo',  
      icon: 'AiOutlineFlag',  
    title: 'Guías de turismo',  
    text: 'Tucumán cuenta con una gran variedad de Hoteles, Cabañas, Estancias Rurales, etc., que ofrecen una gama de opciones de acuerdo a tu presupuesto y preferencias. Podés consultar el listado de alojamientos aquí. ',   
    img: '/images/planifica/alojamiento.jpg'  }, 
  { name: 'Itinerarios',  
      icon: 'AiOutlineSchedule',  
    title: 'Itinerarios',  
    text: 'Si querés conocer todos los atractivos que Tucumán tiene para ofrecerte y no contás con vehículo propio, o no querés conducir para no perderte todas las maravillas del paisaje, no te preocupes. Aquí te dejamos los horarios de los micros a todos los puntos turísticos de nuestra provincia, para que puedas armar tu propio itinerario.',   
    img: '/images/planifica/eventos.jpg'  }, 
  { name: 'Mapas y folletos',  
      icon: 'HiOutlineMap',  
    title: 'Mapas y folletos',  
    text: 'Tucumán cuenta con una gran variedad de Hoteles, Cabañas, Estancias Rurales, etc., que ofrecen una gama de opciones de acuerdo a tu presupuesto y preferencias. Podés consultar el listado de alojamientos aquí. ',    
    img: '/images/planifica/alojamiento.jpg'  }, 
];