const PrestadoresData = [
  {
    titulo: "NOMBRE DE PRESTARDOR",
    subtitulo: "Nombre y apellido del prestador",
    direccion: "Dirección del prestador N° 1456",
    localidad: ["Yerba Buena"],
    actividades: ["Trekking baja y moderada dificultad"],
    contacto: "(0381)45665484",
    email: "correodelprestador@mail.com",
    web: "www.prestador.web.com",
    facebook:
      "https://www.facebook.com/people/Amigos-de-la-Monta%C3%B1a/100063643690242/",
    instagram: "https://www.instagram.com/amigosmonta.tuc/?hl=es ",
    rrss: "",
  },
  {
    titulo: "NOMBRE DE PRESTARDOR",
    subtitulo: "Nombre y apellido del prestador",
    direccion: "Dirección del prestador N° 1456",
    localidad: ["San Miguel de Tucumán"],
    actividades: ["Trekking", "safaris fotográficos", "senderismo","cabalgatas."],
    contacto: "(0381)45665484",
    email: "correodelprestador@mail.com",
    web: "www.prestador.web.com",
    facebook: "https://www.facebook.com/CochaSafaris/?locale=es_LA ",
    instagram: "https://www.instagram.com/cochasafaris/?hl=es-la ",
    rrss: "",
  },
  {
    titulo: "NOMBRE DE PRESTARDOR",
    subtitulo: "Nombre y apellido del prestador",
    direccion: "Dirección del prestador N° 1456",
    localidad: ["Lules"],
    actividades: ["Trekking", "Senderismo", "baja dificultad"],
    contacto: "(0381)45665484",
    email: "correodelprestador@mail.com",
    web: "www.prestador.web.com",
    facebook: "https://www.facebook.com/venezianogabriel/ ",
    instagram: "https://www.instagram.com/purix_trekking/?hl=es",
    rrss: "",
  },
  {
    titulo: "NOMBRE DE PRESTARDOR",
    subtitulo: "Nombre y apellido del prestador",
    direccion: "Dirección del prestador N° 1456",
    localidad: ["Yerba Buena"],
    actividades: ["Trekking  baja y moderada dificultad"],
    contacto: "(0381)45665484",
    email: "correodelprestador@mail.com",
    web: "www.prestador.web.com",
    facebook: "",
    instagram: "https://www.instagram.com/airesdemontana_tucuman/?hl=af",
    rrss: "",
  },
  {
    titulo: "NOMBRE DE PRESTARDOR",
    subtitulo: "Nombre y apellido del prestador",
    direccion: "Dirección del prestador N° 1456",
    localidad: ["San Miguel de Tucumán"],
    actividades: ["Trekking"],
    contacto: "(0381)45665484",
    email: "correodelprestador@mail.com",
    web: "www.prestador.web.com",
    facebook: "https://www.facebook.com/pirkasgrupodemontana/ ",
    instagram: "https://www.instagram.com/pirkasgrupode_montana/?hl=es",
    rrss: "",
  },

  {
    titulo: "NOMBRE DE PRESTARDOR",
    subtitulo: "Nombre y apellido del prestador",
    direccion: "Dirección del prestador N° 1456",
    localidad: ["San Miguel de Tucumán"],
    actividades: ["Trekking", "Senderismo"],
    contacto: "(0381)45665484",
    email: "correodelprestador@mail.com",
    web: "www.prestador.web.com",
    facebook: "https://www.facebook.com/CFSENDERISMO/?locale=es_LA",
    instagram: "https://www.instagram.com/senderismocf/?hl=es ",
    rrss: "",
  },
  
];
export default PrestadoresData;
