const PrestadoresData = [
  {
    titulo: "AMIGOS DE LA MONTAÑA – TA0001-P",
    subtitulo: "Martínez, Facundo",
    direccion: "Manzana i casa 8 Barrio El Bernel- Yerba Buena",
    localidad: ["Yerba Buena"],
    actividades: ["Trekking baja y moderada dificultad"],
    contacto: "(0381)4485418",
    email: "facundomartinez29@yahoo.com.ar",
    web: "",
    facebook:
      "https://www.facebook.com/people/Amigos-de-la-Monta%C3%B1a/100063643690242/",
    instagram: "https://www.instagram.com/amigosmonta.tuc/?hl=es ",
    rrss: "",
  },
  {
    titulo: "COCHA SAFARIS – TA 0002-D",
    subtitulo: "Pino Coviello Jerónimo",
    direccion: "25 de Mayo 545 2 D- San Miguel de Tucumán",
    localidad: ["San Miguel de Tucumán"],
    actividades: [
      "Trekking",
      "safaris fotográficos",
      "senderismo",
      "cabalgatas.",
    ],
    contacto: "(0381)6384017",
    email: "cochasafaris@gmail.com",
    web: "http://www.cochasafaris.com",
    facebook: "https://www.facebook.com/CochaSafaris/?locale=es_LA ",
    instagram: "https://www.instagram.com/cochasafaris/?hl=es-la ",
    rrss: "",
  },
  {
    titulo: "PURIX – TA0003-P",
    subtitulo: "Veneziano José Luis Gabriel",
    direccion: "Bo. UOM Mzana. A, Block Nro 7, Dpto 3- Lules",
    localidad: ["Lules"],
    actividades: ["Trekking", "Senderismo", "baja dificultad"],
    contacto: "(0381)3595815",
    email: "purixtrekking@gmail.com",
    web: "",
    facebook: "https://www.facebook.com/venezianogabriel/ ",
    instagram: "https://www.instagram.com/purix_trekking/?hl=es",
    rrss: "",
  },
  {
    titulo: "AIRES DE MONTAÑA – TA0004-P",
    subtitulo: "Iramain, Sylvina",
    direccion: "Salta 1050 PB Dpto D- Yerba Buena",
    localidad: ["Yerba Buena"],
    actividades: ["Trekking  baja y moderada dificultad"],
    contacto: "(0381)5108902",
    email: "airesdemontana@gmail.com",
    web: "",
    facebook: "",
    instagram: "https://www.instagram.com/airesdemontana_tucuman/?hl=af",
    rrss: "",
  },
  {
    titulo: "PIRKAS GRUPO DE MONTAÑA – TA0005-P",
    subtitulo: "Willigs, Nelson",
    direccion: "Jujuy 1116- San Miguel de Tucuman",
    localidad: ["San Miguel de Tucumán"],
    actividades: ["Trekking"],
    contacto: "(0381)5984698",
    email: "nelson_willigs@hotmail.com",
    web: "",
    facebook: "https://www.facebook.com/pirkasgrupodemontana/ ",
    instagram: "https://www.instagram.com/pirkasgrupode_montana/?hl=es",
    rrss: "",
  },

  {
    titulo: "C.F. SENDERISMO - TA0006-D",
    subtitulo: "Figueroa Carlos David",
    direccion: "Pje. Cesar Carman Nº 3881",
    localidad: ["San Miguel de Tucumán"],
    actividades: ["Trekking", "Senderismo"],
    contacto: "(0381)4479605 / 4355286",
    email: "cdfigueroa621@outlook.com",
    web: "https://www.cf-wamos.tur.ar/ ",
    facebook: "https://www.facebook.com/CFSENDERISMO/?locale=es_LA",
    instagram: "https://www.instagram.com/senderismocf/?hl=es ",
    rrss: "",
  },
  {
    titulo: "+40 PUNTO BIKE",
    subtitulo: "",
    direccion: "",
    localidad: ["El Cadillal"],
    actividades: ["Alquiler de Bicicletas", "Mountain Bike"],
    contacto: "(0381)4099703",
    email: "ecolombres@arnet.com.ar",
    web: "",
    facebook: "",
    instagram:
      "https://www.instagram.com/mas40puntobike/?igshid=MDM4ZDc5MmU%3D",
    rrss: "",
  },
  {
    titulo: "SENDEROS DEL TAFÍ – TA0008-P",
    subtitulo: "Rearte, Constanza",
    direccion: "Barrio 220 viviendas, Mzna I casa nº5- Tafí Viejo",
    localidad: ["Tafí Viejo"],
    actividades: ["Trekking"],
    contacto: "(0381)6447687",
    email: "rearteconty@gmail.com",
    web: "",
    facebook: "https://www.facebook.com/senderosdeltafi/ ",
    instagram: "https://www.instagram.com/senderos_del_tafi/?hl=es-la ",
    rrss: "",
  },

  {
    titulo: "JARDIN DE LA REPUBLICA – TA0019-P",
    subtitulo: "Ivanna Yanet Salvatierra Diaz",
    direccion: "Álvarez Condarco 125, Bo. Sur, Famaillá",
    localidad: ["Álvarez Condarco 125, Bo. Sur, Famaillá"],
    actividades: ["Trekking"],
    contacto: "3816684083",
    email: "iviysd@gmail.com",
    web: "",
    facebook: "",
    instagram: "",
    rrss: " ",
  },
  {
    titulo: "MOVI AVENTURA – TA009-P",
    subtitulo: "Gasco Matias Ramón",
    direccion: "9 de Julio 331, 1ºA - San Miguel de Tucumán",
    localidad: ["San Miguel de Tucumán"],
    actividades: ["Trekking"],
    contacto: "(03865)613650",
    email: "matias.gasco89@gmail.com",
    web: "https://movi-aventuras.negocio.site/",
    facebook: "https://www.facebook.com/Moviaventura/ ",
    instagram: "https://www.instagram.com/moviaventura/?hl=es",
    rrss: " ",
  },
  {
    titulo: "SUYAI – TA0010-P",
    subtitulo: "Visedo Maria Lorena",
    direccion: "Manuel Alberti 212 - San Javier",
    localidad: ["San Javier"],
    actividades: ["Cabalgatas", "Trekking", "Mountain Bike."],
    contacto: "(0381)5265036",
    eMail: "lorena-visedo@hotmail.com",
    web: "",
    facebook: "https://www.facebook.com/suyaicabalgatas/",
    instagram: "https://www.instagram.com/suyaicabalgatasytrekking/?hl=es ",
    rrss: " ",
  },
  {
    titulo: "CAMINANTES DE MONTAÑA – TA0011-P",
    subtitulo: "Di Berto Renzo Paolo",
    direccion: "Miguel Lillo N° 2321 - Concepción",
    localidad: ["Concepción"],
    actividades: [
      "Cascada de Los Pizarros (La Cocha)",
      "Cascadas y túneles de Rumi Punco (La Cocha)",
      "Parque Nacional Aconquija (Guía habilitado de Parque Nacional Aconquija)",
      "Casa de Piedra, estancia Jaya (Concepción)",
      "Laguna del Tesoro (Concepción)",
      "Puesto La Mesada (Concepción)",
      "Refugio La Cascada (Concepción)",
      "Campo de Las Azucenas, Toma de Los Reales (Monteros)",
      "Quebrada del Portugués (Monteros)",
      "Túnel de Lules (Lules)",
      "Potrero de Las Tablas (Lules)",
      "Mundo Nuevo (Villa Nougues)",
      "La Mota (San Javier)",
      "Cruz de Yampa (Raco)",
      "Alfama (Raco)",
      "Cascadas de Villa Padre Monti (Burruyacú)",
    ],
    contacto: "(03865)675666",
    email: "equipocaminantes@gmail.com",
    web: "",
    facebook: "https://www.facebook.com/CaminantesDeMontaniaa/?locale=es_LA ",
    instagram: "https://www.instagram.com/caminantesdemontana/?hl=es ",
    rrss: "",
  },
  {
    titulo: "ADRI Y FER GUÍAS - TA0012-P",
    subtitulo: "Latorre Adriana Alicia",
    direccion: "Bº San Rosa S/N",
    localidad: ["Tafí del Valle"],
    actividades: [
      "Avistaje de Aves",
      "Trekking",
      "Mountain Bike",
      "Kayak",
      "Alta Montaña",
    ],
    contacto: "3814015179",
    email: "adriyferguias@gmail.com",
    web: "https://tafidelvalle.com/adri-y-fer-experiencias",
    facebook: "",
    instagram: "https://www.instagram.com/adriyferguias/?hl=es-la ",
    rrss: "",
  },
  {
    titulo: "TUCUMAN KAYAK  CLUB – TA0013-P",
    subtitulo: "Budeguer Diego Sebastián",
    direccion: "Zona de Playa- Dique Celestino Gelsi- Sector 1- El Cadillal",
    localidad: ["El Cadillal"],
    actividades: ["Trekking", "Alquiler de kayaks", "Paseos en kayak"],
    contacto: "(0381)5195817",
    email: "tucumankayakclub@gmail.com",
    web: "https://linktr.ee/tucumankayakclub",
    facebook: "https://www.facebook.com/tkcturismoaventura/ ",
    instagram: "https://www.instagram.com/tucumankayakclub/?hl=es ",
    rrss: "",
  },
  {
    titulo: "SP AVENTURAS –TA0014-P",
    subtitulo: "Díaz, Matías",
    direccion: "24 de septiembre s/n- San Pablo",
    localidad: ["San Pablo"],
    actividades: ["Trekking", "Mountain bike"],
    contacto: "(0381)4097105",
    email: "spaventuratour@gmail.com",
    web: "https://www.spaventura.com.ar/",
    facebook: "https://www.facebook.com/SPAventura22/",
    instagram: "https://www.instagram.com/spaventura_tour/?hl=es-la ",
    rrss: "",
  },
  {
    titulo: "KAYAK Y TREKKING – TA0015-P",
    subtitulo: "Rodríguez Victor Horacio",
    direccion: "San Lorenzo 987 Piso 2° dto.B - San Miguel de Tucumán",
    localidad: ["San Miguel de Tucumán"],
    actividades: ["Trekking", "kayak"],
    contacto: "(0381)5904073",
    email: "kayakytrekking@gmail.com",
    web: "",
    facebook: "",
    instagram: "https://www.instagram.com/kayakytrekking/",
    rrss: "",
  },

  {
    titulo: "CABRA HORCO EXPEDICIONES – TA0016-P",
    subtitulo: "Nicolás Paz Posse",
    direccion: "Villa Turística Raco- Tafí Viejo",
    localidad: ["Tafí Viejo"],
    actividades: ["Cabalgatas", "Trekking"],
    contacto: "(0381)6788399",
    email: "info@cabrahorco.com.ar",
    web: "www.cabrahorco.com.ar",
    facebook: "https://www.facebook.com/cabrahorco/?locale=es_LA ",
    instagram: "",
    rrss: "",
  },
  {
    titulo: "VUELA TUCUMAN – TA0017-P",
    subtitulo: "Julio Ignacio Ortiz",
    direccion: "San Martín 1600 Lote 54- Bo La Cañadita- Yerba Buena",
    localidad: ["Yerba Buena"],
    actividades: ["Parapente"],
    contacto: "(0381)6888677",
    email: "j_ignacio-ortiz@hotmail.com",
    web: "",
    facebook: "https://www.facebook.com/vuelatucuman.ok ",
    instagram: "",
    rrss: "",
  },
  {
    titulo: "LOS PINOS- SAN JAVIER  – TA0018-P",
    subtitulo: "Raúl Ignacio Fort",
    direccion: "Ruta 338, Km 27 – Los Pinos-San Javier",
    localidad: ["San Javier"],
    actividades: ["Parapente"],
    contacto: "(0381)6408593",
    email: "raulitofort@gmail.com",
    web: "www.lospinosparapente.com.ar",
    facebook: "",
    instagram: "",
    rrss: "",
  },
  {
    titulo: "JARDÍN DE LA REPUBLICA  – TA0019-P",
    subtitulo: "Ivanna Yanet Salvatierra Diaz",
    direccion: "",
    localidad: [""],
    actividades: ["Trekking"],
    contacto: "(0381)6684083",
    email: "iviysd@gmail.com",
    web: "",
    facebook: "",
    instagram: "",
    rrss: "",
  },
  {
    titulo: "VOLAR EXCURSIONES WAKU – TA0020-D",
    subtitulo: "Mario Martín Sueldo",
    direccion: "Jujuy 277 – San Miguel de Tucumán - Ruta 338 Km 27 – LOMA BOLA",
    localidad: ["San Miguel de Tucumán"],
    actividades: ["Parapente"],
    contacto: "(0381)5239572",
    email: "sueldo@hotmail.com; volarexcursiones@gmail.com",
    web: "https://waku.com.ar/ ",
    facebook: " ",
    instagram: "https://www.instagram.com/waku.parapente/",
    rrss: "",
  },
  {
    titulo: "LOMA BOLA PARAPENTE – TA0021-P",
    subtitulo: "Bujazha, Sergio",
    direccion: " San Javier - Ruta 338 Km 27 – LOMA BOLA",
    localidad: ["San Javier", "Ruta 338 Km 27 – LOMA BOLA"],
    actividades: ["Parapente", "Vuelos Biplaza"],
    contacto: "(0381)4908454",
    email: "sbujazha@gmail.com",
    web: "http://www.lomabola.com.ar",
    facebook: "https://www.facebook.com/LomaBolaParapente/?locale=es_LA",
    instagram: "https://www.instagram.com/lomabolaparapente/?hl=es ",
    rrss: "",
  },
  {
    titulo: "SW TUCUMAN AVENTUR – TA0022-P",
    subtitulo: "Wilde, Sergio Ladislao",
    direccion: "25 de mayo 521, piso 5, depto D- San Miguel de Tucumán",
    localidad: ["San Miguel de Tucumán"],
    actividades: [
      "Canyoning",
      "Cabalgatas",
      "Trekkings",
      "Canotaje",
      "Mountain Bike",
      "Paseos en Lancha",
      "Buceo Deportivo",
      "Banana Acuática",
    ],
    contacto: "(0381)4923013 / (0381)6785988",
    email: "sergiolwilde@yahoo.com",
    web: "http://swtucumanaventuras.com.ar/",
    facebook: "https://www.facebook.com/SWTucumanAventuras/?locale=es_LA",
    instagram: "https://www.instagram.com/sw_tucuman_aventuras/?hl=es",
    rrss: "",
  },
  {
    titulo: "NAMASTREK – TA0023-P",
    subtitulo: "Sergio Rene Sanchez ",
    direccion: "Gral. Paz 2378- San Miguel de Tucumán - 4000",
    localidad: [" San Miguel de Tucumán "],
    actividades: ["Trekking"],
    contacto: "(0381)4471273",
    email: "gersiore@gmail.com",
    web: "",
    facebook: "https://www.facebook.com/namastrekk/?locale=es_LA ",
    instagram: "https://www.instagram.com/namastrek/?hl=es ",
    rrss: "",
  },
  {
    titulo: "KAYAKS DEL NOA EXPEDICIONES ACUÁTICAS – TA0024-P",
    subtitulo: "Suarez, Walter Mario",
    direccion: "",
    localidad: [
      "Diques: El Cadillal – La Angostura – Escaba – Frontal",
      "San Miguel de Tucumán",
    ],
    actividades: ["Kayaks", "Canotaje", "Pesca  Deportiva"],
    contacto: "(0381)4915969/ (0381)4728837",
    email: "kayaksdelnoa@gmail.com",
    web: "",
    facebook: "https://www.facebook.com/kayaksnoa",
    instagram: "https://www.instagram.com/kayaksdelnoa/?hl=es ",
    rrss: "",
  },
  {
    titulo: "FUNDACION COQUENA DTS (Desarrollo Tur. Susutentable) – TA0025-P",
    subtitulo: "Ma. Jimena Sánchez",
    direccion: "9 de Julio esq. Las Heras s/n- San Pedro de Colalao",
    localidad: ["San Pedro de Colalao"],
    actividades: ["Trekking", "Cabalgatas"],
    contacto: "(381)4723352 / (381)4901749 / (381)5743906",
    email: "sanpedrocolalao@gmail.com",
    web: "http://fundacioncoquena.org/",
    facebook: "https://www.facebook.com/coquenadts/",
    instagram: "https://www.instagram.com/fundacoquena",
    rrss: "",
  },
  {
    titulo: "TREKKING TUCUMAN – TA0026-P",
    subtitulo: "Juan Osvaldo Monteros",
    direccion: "Constancio Vigil 2222 dpto 22- Yerba Buena",
    localidad: ["Yerba Buena"],
    actividades: ["Trekking"],
    contacto: "(0381)6300317",
    email: "trekkingtucuman26@gmail.com",
    web: "",
    facebook: "",
    instagram: "https://www.instagram.com/trekkingtucuman/?hl=es-la ",
    rrss: "",
  },

  {
    titulo: "SENDERO TUCUMANO – TA0027-P",
    subtitulo: "Maximiliano Ruben Acuña Pinto",
    direccion: "Bo El Portal del Cerro Mza.C Lote 17- Yerba Buena",
    localidad: ["Bo El Portal del Cerro Mza.C Lote 17 - Yerba Buena"],
    actividades: ["Trekking"],
    contacto: "3815746224",
    email: "teamacunatrail@yahoo.com",
    web: "",
    facebook: "",
    instagram: "",
    rrss: " Instagram: MAXI_ACUNNA",
  },

  {
    titulo: "ECO AVENTURAS TUCUMAN – TA0028-P",
    subtitulo: "Pablo Roberto Cena",
    direccion: "Estados Unidos 35 - San Miguel de Tucumán",
    localidad: ["San Miguel de Tucumán"],
    actividades: ["Trekking"],
    contacto: "(0381)6045969",
    email: "pablocena04@gmail.com; ecoaventurastuc@gmail.com",
    web: "",
    facebook: "https://www.facebook.com/p/Eco-Aventuras-Xtreme",
    instagram: "https://www.instagram.com/ecoaventurastuc",
    rrss: "",
  },
  {
    titulo: "SOS TIERRA AVENTURAS - TA0029-P",
    subtitulo: "Pablo Humberto Cordoba",
    direccion:
      "Av Presidente Perón 2707- Bo Horco Molle, Mzna B- casa 18 – Yerba Buena",
    localidad: ["Yerba Buena"],
    actividades: [
      "Trekking",
      "Mountain Bike",
      "Canyoning",
      "Kayak",
      "Safari fotográfico",
    ],
    contacto: "(0381)2374444",
    email: "sostierratucuman@gmail.com",
    web: "https://www.instagram.com/pantera.outdoor/",
    facebook: "https://www.facebook.com/SOSTierraTucuman ",
    instagram: "https://www.instagram.com/sostierracomunidad/?hl=es ",
    rrss: "",
  },
  {
    titulo: "CALCHABIKE - TA0030-D",
    subtitulo: "Nicolás Paez Salas",
    direccion: "Bo Altoverde, Mzna C- lote 13 – Localidad: Cebil Redondo",
    localidad: ["Bo Altoverde, Mzna C- lote 13 – Localidad: Cebil Redondo"],
    actividades: ["Cicloturismo"],
    contacto: "(0381)5425188",
    email: "calchabike@gmail.com",
    web: "",
    facebook: "",
    instagram: "",
    rrss: "",
  },
  {
    titulo: "VOLAR EN PARAPENTE - TA0033-P",
    subtitulo: "Leonardo Daniel Varea",
    direccion: "Loma Bola – San Javier/ Nogalito s/n Lules",
    localidad: ["Loma Bola – San Javier/ Nogalito s/n Lules"],
    actividades: ["Parapente"],
    contacto: "(0381)5771260",
    email: "varealeaonardo47@gmail.com",
    web: "",
    facebook: "",
    instagram: "",
    rrss: "",
  },
  {
    titulo: "POWELL´S GROUP - TA0034-P",
    subtitulo: "Silvestre Alejandro Powell",
    direccion: "Brasil 1697- Yerba Buena Tucuman",
    localidad: ["Brasil 1697- Yerba Buena Tucuman"],
    actividades: ["Trekking"],
    contacto: "(0381)3665393",
    email: "alejandro.s.powell@gmail.com",
    web: "",
    facebook: "",
    instagram: "",
    rrss: "",
  },
  {
    titulo: "HIGH TREK OUTDOORS - TA0032-P",
    subtitulo: "Marcelo Fabian Villagra",
    direccion: "Bo. APUNT Mzna.C Casa 11 – Yerba Buena",
    localidad: ["Yerba Buena"],
    actividades: ["Trekking"],
    contacto: "(0381)6490247",
    email: "mvtrainner@hotmail.com",
    web: "https://linktr.ee/hightrekoutdoors",
    facebook: "https://www.facebook.com/VillagraMarcelo78/",
    instagram: "https://www.instagram.com/high_trekoutdoors/ ",
    rrss: "",
  },
  {
    titulo: "DOS POZOS TURISMO ACTIVO - TA0036-P",
    subtitulo: "Fadua Yamila Dilascio",
    direccion: "9 de Julio 44 - San Pedro de Colalao",
    localidad: ["San Pedro de Colalao"],
    actividades: [
      "Trekking",
      "Cabalgatas",
      "Mountain Bike",
      "Safari Fotográfico",
    ],
    contacto: "(0381)5830889 / (0381)4453244 ",
    email: "sanpedrodecolalao@gmail.com",
    web: "",
    facebook: "",
    instagram: "https://www.instagram.com/refugiodospozos/",
    rrss: "",
  },
  {
    titulo: "PESCA EL MOLLAR - TA0035-P",
    subtitulo: "Miguel Angel Quesada",
    direccion: "Manuel Alberti 331- San Miguel de Tucumán",
    localidad: [" San Miguel de Tucumán"],
    actividades: [
      "Kayak",
      "Pesca Deportiva",
      "Paseos en Embarcaciones a Motor",
    ],
    contacto: "(0381)6435558",
    email: "miguelangelquesada@hotmail.com",
    web: "",
    facebook: "",
    instagram: "",
    rrss: "",
  },
  {
    titulo: "PESCA EL PELAO - TA0037-P",
    subtitulo: "Eduardo Monasterio",
    direccion: "Av. Los Menhires s/n – El Mollar",
    localidad: [" El Mollar"],
    actividades: ["Pesca Deportiva", "Paseos en Lancha"],
    contacto: "(0381)3405505",
    email: "eledu1022@gmail.com",
    web: "",
    facebook: "https://www.facebook.com/PescaElPelao/",
    instagram: "",
    rrss: "",
  },
  {
    titulo: "PARAPENTE SAN JAVIER - TA0031-D",
    subtitulo: "Franco Rubén Varea",
    direccion: "Ruta Prov. 338 km 27.5 – Anta Muerta- San Javier",
    localidad: ["Ruta Prov. 338 km 27.5 – Anta Muerta - San Javier"],
    actividades: ["Parapente"],
    contacto: "(0381)4017997",
    email: "vareafranco@gmail.com",
    web: "",
    facebook: "",
    instagram: "",
    rrss: "",
  },
  {
    titulo: "RAKI - TA0038-P",
    subtitulo: "RAKI S.A.S.",
    direccion: "Av. Aconquija 3210 – Yerba Buena",
    localidad: ["Yerba Buena"],
    actividades: ["Tirolesa"],
    contacto: "(0381)5675037",
    email: "info@rakitucuman.com",
    web: "https://www.rakitucuman.com/",
    facebook: "https://www.facebook.com/rakitucuman/",
    instagram: "https://www.instagram.com/rakitucuman/?hl=es",
    rrss: "",
  },
  {
    titulo: "INTI SUYO - TA0039-P",
    subtitulo: "Enzo Carlos Palladini",
    direccion: "Entre Ríos 589 – Tafí Viejo",
    localidad: ["Tafí Viejo"],
    actividades: ["Trekking"],
    contacto: "(0381)3024632",
    email: "enzopalladini@hotmail.com",
    web: "",
    facebook: "",
    instagram: "",
    rrss: "",
  },
  {
    titulo: "VOLAR EN TUCUMAN - TA0040-P",
    subtitulo: "María Mercedes Gijon",
    direccion: "Juan B. Terán 20- dto. 108- Yerba Buena",
    localidad: ["Yerba Buena"],
    actividades: ["Parapente"],
    contacto: "(0381)4629458",
    email: "volarentucuman@gmail.com",
    web: "http://www.volarentucuman.com.ar/ ",
    facebook: "https://www.facebook.com/volarentucuman/",
    instagram: "https://www.instagram.com/volarentucuman/",
    rrss: "",
  },
  {
    titulo: "AIRE DE MONTAÑA DEPORTE Y TURISMO DE AVENTURA - TA0041-P",
    subtitulo: "Cristian Ricardo Mamaní",
    direccion: "Bo. San Cayetano – La Ovejería- Tafí del Valle",
    localidad: ["La Ovejería- Tafí del Valle"],
    actividades: ["Trekking", "Mountain Bike", "Kayak"],
    contacto: "(0381)5462502",
    email: "aventurapinosport@gmail.com",
    web: "",
    facebook: "https://www.facebook.com/AIREDEMONTANATAFIDELVALLE",
    instagram: "https://www.instagram.com/aventura_pinosport/ ",
    rrss: "",
  },
  {
    titulo: "TITANIUM SALUD & DEPORTE - TA0042-P",
    subtitulo: "Andrés Pablo Palacios",
    direccion: "Junin  645- S. M de Tucuman",
    localidad: ["San Miguel de Tucumán"],
    actividades: ["Trekking", "Navegación", "Kayak"],
    contacto: "(0381)5417323",
    email: "andrespablopalacios@gmail.com",
    web: "",
    facebook: "https://www.facebook.com/TitaniumTucuman/?locale=es_LA ",
    Intagram: "https://www.instagram.com/titanium.tucuman/?hl=es-la ",
    rrss: "",
  },
  {
    titulo: "TREKKING YUNGAS TUCUMANAS - TA0043-P",
    subtitulo: "Héctor Javier Alejandro Rasgido Leal",
    direccion: "Anca Juli- Tafi Viejo",
    localidad: ["Tafi Viejo"],
    actividades: ["Trekking"],
    contacto: "(0381)6982124 / (0381)5714384",
    email: "ale_rasgido@hotmail.com.ar , rasgido-luis@hotmail.com ",
    web: "",
    facebook: "",
    instagram: "",
    rrss: "",
  },
  {
    titulo: "PESCA EL MOLLAR - TA0035-P",
    subtitulo: "Miguel Angel Quesada",
    direccion: "Manuel Alberti 331- San Miguel de Tucuman",
    localidad: ["San Miguel de Tucuman"],
    actividades: [
      "Kayak",
      "Pesca Deportiva",
      "Paseos en Embarcaciones a Motor",
    ],
    contacto: "(0381)6435558",
    email: "miguelangelquesada@hotmail.com",
    web: "",
    rrss: "",
  },
  {
    titulo: "COMPLEJO TWISTER - TA0044-P",
    subtitulo: "Ramon Heredia",
    direccion:
      "Leandro Diaz s/n- Sector 8- mzna 1- casa 34 B- Lomas de Tafi- Tafi Viejo",
    localidad: ["Tafí Viejo"],
    actividades: ["Tirolesa"],
    contacto: "(0381)3404522",
    email: "menhires@gmail.com",
    web: "",
    facebook: "",
    instagram: "",
    rrss: "",
  },
  {
    titulo: "DE TREKKING Y AVENTURAS TUCUMAN - TA0045-P",
    subtitulo: "Guadalupe Calle",
    direccion: "Camino del Perú 2100, San Miguel de Tucumán",
    localidad: ["San Miguel de Tucumán"],
    actividades: ["Trekking"],
    contacto: "(0381)3816041766",
    email: "trekking.aventura.tuc@gmail.com",
    web: "https://linktr.ee/de.trekking.aventura.tucuman",
    facebook: " https://www.facebook.com/trekking.aventuratuc",
    instagram: "https://www.instagram.com/de.trekking.aventura.tucuman/ ",
    rrss: "",
  },
  {
    titulo: "HORIZONTE AVENTURAS - TA0046-P",
    subtitulo: "Leandro Ezequiel Conde",
    direccion: "Mariano Moreno 341, San Miguel de Tucumán",
    localidad: ["San Miguel de Tucumán"],
    actividades: [
      "Cabalgatas",
      "Trekking",
      "Rappel",
      "Mountain Bike",
      "Alta Montaña",
    ],
    contacto: "(0381)6431085",
    email: "horizonte.turismo@gmail.com",
    web: "",
    facebook: "",
    instagram: "",
    rrss: "",
  },
  {
    titulo: "QUENQUIANDO CERROS  - TA-0047-P",
    subtitulo: "ASOCIACIÓN CIVIL CO. PRO. DE. SA",
    direccion: "Av. Independencia N°873, Tafí Viejo",
    localidad: ["Tafí Viejo"],
    actividades: [
      "Trekkingl",
      "Mountain Bike",
      "Canyoning",
      "Safari Fotográfico",
      "Observación de Flora y Fauna",
    ],
    contacto: "(0381)6325578",
    email: "quenquiandocerros@gmail.com",
    web: "https://quenquiandocerros.blogspot.com/",
    facebook:
      "https://www.facebook.com/profile.php?id=100090704928005&mibextid=ZbWKwL",
    instagram: "https://www.instagram.com/quenquiandocerros",
    rrss: "",
  },
  {
    titulo: "MERY CABALGATAS - TA0048-P",
    subtitulo: "Bárbara Natali Sosa",
    direccion: "Cerro San Javier, Calle 14 y 15, San Javier ",
    localidad: ["San Javier"],
    actividades: ["Cabalgatas", "Trekking"],
    contacto: "(0381)4565096",
    email: "natalipastillera2016@gmail.com",
    web: "",
    facebook: "",
    instagram: "",
    rrss: "",
  },
  {
    titulo: "KILLA RUNA -  TA-0049-P",
    subtitulo: "Javier Federico Frizzera",
    direccion: "Ruta Nº 308 s/nº - Escaba, Bautista Alberdi ",
    localidad: ["Bautista Alberdi"],
    actividades: [
      "Cabalgatas",
      "Trekking",
      "MountainBike",
      "Kayak",
      "Safari fotografico",
      "Ciclo turismo",
    ],
    contacto: "(3865)555394",
    email: "javierfrizzera@gmail.com, javierfrizzera@hotmail.com",
    web: "",
    facebook: "",
    instagram: "",
    rrss: "",
  },
];
export default PrestadoresData;
